port: 8000

auth:
  hash_salt: "hash_salt"
  signing_key: "signing_key"
  token_ttl: 86400

db:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "todo"
  sslname: disable